<h2 style="color:navy" align="center">

<h2 style="color:navy"> What is NumPy Array Iterating ? </h2>

* Iterating means going through elements one by one.
* As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

In [1]:
#Iterate on the elements of the following 1-D array:

import numpy as np

arr = np.array([1, 2, 3,4,5,6])

for x in arr:
    print(x)

1
2
3
4
5
6


In [2]:
#Iterate on the elements of the following 2-D array:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [3]:
# Iterate on each scalar element of the 2-D array:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)
    for y in x:
        print(y)

[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [5]:
for i in arr[1]:
    print(i)

4
5
6


In [6]:
#Iterate on the elements of the following 3-D array:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(len(arr))
print(arr[0])
print(arr[1])


2
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [7]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(len(arr))

for x in arr:
    print(x)

2
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [8]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(len(arr))

for x in arr:
    #print(x)
    for y in x:
        print(y)

2
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [9]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(len(arr))

for x in arr:
    for y in x:
        for z in y:
            print(z)

2
1
2
3
4
5
6
7
8
9
10
11
12


<h2 style="color:navy">What is NumPy Array Joining ?</h2>

* Joining means putting contents of two or more arrays in a single array.
* We pass a sequence of arrays that we want to join to the concatenate() function .

In [2]:
#Join two arrays

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)


[1 2 3 4 5 6]
[5 7 9]


In [4]:
import numpy as np

arr1 = np.array([[1, 2, 3],[4, 5, 6]])

arr2 = np.array([[7, 8, 9],[10, 11, 12]])

newarr1 = np.concatenate((arr1, arr2))

newarr2 = np.concatenate((arr1, arr2),axis=1)

# axis : int, optional
#     The axis along which the arrays will be joined.  If axis is None,
#     arrays are flattened before use.  Default is 0.

print(newarr1)
print()
print(newarr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### Joining Arrays Using Stack Functions
* Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

In [5]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr_1 = np.stack((arr1, arr2), axis=0)
arr_2 = np.stack((arr1, arr2), axis=1)

print(arr_1)
print()
print(arr_2)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


### Stacking Along Rows
* NumPy provides a helper function: hstack() to stack along rows.

In [6]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


### Stacking Along Columns
* NumPy provides a helper function: vstack()  to stack along columns.

In [7]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


### Stacking Along Height (depth)
* NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

In [8]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


<h2 style="color:navy"> What is Splitting NumPy Arrays ? ? </h2>
    
* Splitting is reverse operation of Joining.

* Joining merges multiple arrays into one and Splitting breaks one array into multiple.

* We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [9]:
#Split the array in 3 parts:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr1 = np.array_split(arr, 1)  #Split the array in 1 parts:
newarr2 = np.array_split(arr, 2)  #Split the array in 2 parts:
newarr3 = np.array_split(arr, 3)  #Split the array in 3 parts:
newarr4 = np.array_split(arr, 4)  #Split the array in 4 parts:
 
print(newarr1)
print()
print(newarr2)
print()
print(newarr3)
print()
print(newarr4)
print()

[array([1, 2, 3, 4, 5, 6])]

[array([1, 2, 3]), array([4, 5, 6])]

[array([1, 2]), array([3, 4]), array([5, 6])]

[array([1, 2]), array([3, 4]), array([5]), array([6])]



In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],[ 4, 5, 6]])

newarr1 = np.array_split(arr, 1, axis=1)  #Split the array in 1 parts:
newarr2 = np.array_split(arr, 2, axis=1)  #Split the array in 2 parts:
newarr3 = np.array_split(arr, 3, axis=1)  #Split the array in 3 parts:
newarr4 = np.array_split(arr, 4, axis=1)  #Split the array in 4 parts:
 
print(newarr1)
print()
print(newarr2)
print()
print(newarr3)
print()
print(newarr4)
print()

### similerlly
* hsplit() 
* vsplit()  
* dsplit().

task : try above keywords .