## Data Types in Python
By default Python have these data types:

* strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
* integer - used to represent integer numbers. e.g. -1, -2, -3
* float - used to represent real numbers. e.g. 1.2, 42.42
* boolean - used to represent True or False.
* complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

## Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type ( void )

### Checking the Data Type of an Array

In [1]:
import numpy as np

In [4]:
arr_1 = np.array([1, 2, 3, 4])
arr_2 = np.array(['apple', 'banana', 'cherry'])

print(arr_1.dtype)
print(arr_2.dtype)

int32
<U6


### Creating Arrays With a Defined Data Type

In [5]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


#### For i, u, f, S and U we can define size as well.

In [7]:
arr = np.array([1, 2, 3, 4], dtype='i')
# Create an array with data type 4 bytes integer
print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


In [8]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [1]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='f')
print(arr)
print(arr.dtype)

In [2]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


## NumPy Array Copy vs View
The Difference Between Copy and View
* The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

* The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

* The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

## Copy

In [3]:
import numpy as np

In [10]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
print(arr)
print("This is x",x)
print()
arr[0] = 42
x[0] = 11
print("This is arr",arr)
print("This is x",x)

[1 2 3 4 5]
This is x [1 2 3 4 5]

This is arr [42  2  3  4  5]
This is x [11  2  3  4  5]


## VIEW:

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
print(arr)
print(x)
print()
x[0] = 12
print("This is arr",arr)
print("This is x",x)

[1 2 3 4 5]
[1 2 3 4 5]

This is arr [12  2  3  4  5]
This is x [12  2  3  4  5]


### Check if Array Owns it's Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

* Every NumPy array has the attribute base that returns None if the array owns the data.

* Otherwise, the base  attribute refers to the original object.

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [4]:
%whos

Variable   Type       Data/Info
-------------------------------
arr        ndarray    5: 5 elems, type `int32`, 20 bytes
np         module     <module 'numpy' from 'c:\<...>ges\\numpy\\__init__.py'>
x          ndarray    5: 5 elems, type `int32`, 20 bytes
y          ndarray    5: 5 elems, type `int32`, 20 bytes


## Shape of an Array
* The shape of an array is the number of elements in each dimension.

In [1]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


## NumPy Array Reshaping
* Reshaping means changing the shape of an array.

In [9]:
# Reshape From 1-D to 2-D
# Example
# Convert the following 1-D array with 12 elements into a 2-D array.

# The outermost dimension will have 4 arrays, each with 3 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
len(arr)
print(arr,arr.shape)
newarr = arr.reshape(3, 4)

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12] (12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 2,3)

print(newarr)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
newarr_2 = arr.reshape(3, 2, 2)

print(newarr_2)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [9]:
newarr_3 = arr.reshape(6, 2, 1)

print(newarr_3)

[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [10]]

 [[11]
  [12]]]


In [10]:
newarr_4 = arr.reshape(6, 1, 2)

print(newarr_4)

[[[ 1  2]]

 [[ 3  4]]

 [[ 5  6]]

 [[ 7  8]]

 [[ 9 10]]

 [[11 12]]]


<h2 style="color:navy">Can We Reshape Into any Shape ? 

In [11]:
#Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension (will raise an error):

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [12]:
#Check if the returned array(by reshape) is a copy or a view:
# if base returns None that means it is copy ,
# or if it returns original array then it is view .
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

print("The example above returns the original array, so it is a view.")

[1 2 3 4 5 6 7 8]
The example above returns the original array, so it is a view.


## Unknown Dimension
You are allowed to have one "unknown" dimension.

* Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

* Pass -1 as the value, and NumPy will calculate this number for you.

In [4]:
#Convert 1D array with 8 elements to 3D array with 2x2 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
newarr = arr.reshape(2, -1, 2)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
newarr = arr.reshape(4, -1, 2)

print(newarr)

[[[1 2]]

 [[3 4]]

 [[5 6]]

 [[7 8]]]


<h2 style="color:navy" >What is Flattening the arrays  ? ?</h2>

### Ans :Flattening array means converting a multidimensional array into a 1D array.

* We can use reshape(-1) to do this.

In [2]:
#Convert the array into a 1D array:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print()
newarr = arr.reshape(-1)

print(newarr)

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


In [8]:
arr_2 = np.array([[1, 2, 3], [4, 5, 6],[22,33,44]])
print(arr_2)
print()
newarr = arr_2.reshape(-1)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [22 33 44]]

[ 1  2  3  4  5  6 22 33 44]


In [10]:
arr_2 = np.array([[1, 2, 3], [4, 5, 6],[22,33,44],[21,32,43]])

newarr = arr_2.reshape(-1,3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [22 33 44]
 [21 32 43]]
